 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
66.112.227.7 - - [13/Jan/2017 02:42:44] "GET / HTTP/1.1" 200 -
66.112.227.7 - - [13/Jan/2017 02:42:44] "GET /static/styles.css HTTP/1.1" 200 -
66.112.227.7 - - [13/Jan/2017 02:42:44] "GET /static/submit.js HTTP/1.1" 200 -
66.112.227.7 - - [13/Jan/2017 02:42:53] "GET / HTTP/1.1" 200 -
[2017-01-13 02:43:38,284] ERROR in app: Exception on /submit [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 44, in queue_run
    image.save(file_path)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/werkzeug/datastructures.py", line 2666, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'primavera/process_queue/1484275418.2831154.jpg'
66.112.227.7 - - [13/Jan/2017 02:43:38] "POST /submit HTTP/1.1" 500 -
